name: analyse

on:
  push:
  pull_request:

jobs:
  analyse:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: [8.2]
        experimental:
          - false

    name: PHP:${{ matrix.php }} Code Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Execute Code Style Analysis
        run: vendor/bin/pint --test

      - name: Execute Static Code Analysis
        run: vendor/bin/phpstan analyse --verbose
